In [1]:
import h5py
import numpy as np


In [2]:
with h5py.File('/home/keshav/MSUtils/data/voroImg_eroded.h5', 'r') as file_msutils:
    # Read the normals from the MSUtils file
    normal_msutils = file_msutils['/dset_0/normals'][...]
    print('msutils normals shape:', normal_msutils.shape)

# Read the normals from the FANS file
with h5py.File('/home/keshav/FANS/test/scratch/test_results.h5', 'r') as file_fans:
    normal_fans = file_fans['/dset_0/eroded_image_results/load0/time_step0/GBnormals'][...]
    print('FANS normals shape:', normal_fans.shape)


msutils normals shape: (128, 128, 128, 3)
FANS normals shape: (128, 128, 128, 3)


In [3]:
np.linalg.norm(normal_fans - normal_msutils)

np.float64(0.0)

In [4]:
np.linalg.norm(normal_msutils - normal_fans)

s_msutils = normal_msutils.reshape((-1,3)).T @ normal_msutils.reshape((-1,3))
s_fans = normal_fans.reshape((-1,3)).T @ normal_fans.reshape((-1,3))

print(s_msutils/len(np.where(np.linalg.norm(normal_msutils, axis=1) > 0)[0]))
print(s_fans/len(np.where(np.linalg.norm(normal_fans, axis=1) > 0)[0]))

[[ 2.42641606e+00 -9.45604269e-36  6.61922988e-35]
 [-9.45604269e-36  2.42641606e+00 -5.91948602e-18]
 [ 6.61922988e-35 -5.91948602e-18  2.42641606e+00]]
[[ 2.42641606e+00 -9.45604269e-36  6.61922988e-35]
 [-9.45604269e-36  2.42641606e+00 -5.91948602e-18]
 [ 6.61922988e-35 -5.91948602e-18  2.42641606e+00]]


In [12]:
# Calculate the sum of normals for both datasets
# Calculate the mean of normals for both datasets
msutils_mean = np.mean(normal_msutils, axis=(0, 1, 2))
fans_mean = np.mean(normal_fans, axis=(0, 1, 2))

# Print the results
print("Mean of MSUtils normals:", msutils_mean)
print("Mean of FANS normals:", fans_mean)



Mean of MSUtils normals: [-0.00774723  0.02164226  0.01886325]
Mean of FANS normals: [-0.00774723  0.02164226  0.01886325]


In [5]:
c_GB = 0.256447
D_bulk = 1.0
D_para = 1e2
D_perp = 1e2
S = s_fans

D_reuss = np.linalg.inv( (1 - c_GB) / D_bulk * np.eye(3)
                            + c_GB * ((D_para -D_perp) / (D_para * D_perp) * S + 1/D_para * np.eye(3)))

D_voigt = ( (1 - c_GB) * D_bulk * np.eye(3)
            + c_GB * ( ( D_perp - D_para) * S + D_para * np.eye(3)))

print(D_reuss)
print(D_voigt)

[[1.34027153 0.         0.        ]
 [0.         1.34027153 0.        ]
 [0.         0.         1.34027153]]
[[26.388253  0.        0.      ]
 [ 0.       26.388253  0.      ]
 [ 0.        0.       26.388253]]
